### ISSUE TITLE
Remove component constraint on Is, As and All

### ISSUE THREAD

**Issue by Eregerog** [XDracam/unity-corelibrary#13]
Unity's get component does not have a component constraint so the user can search for components that implement an interface
I'd be nice to have this feature in the corelob as well

**Comment by XDracam** [comment]
Very nice contribution. Will do.

Replacing the constaint with a simple `: class` so that one does not try to get a value type as component.

**Comment by XDracam** [comment]
Also removing the `where T : Component` constaints on `AssignComponent` and `AssignIfAbsent` so you can elegantly assign interface types as well.
