### ISSUE TITLE
MarkSceneDirty when creating LazySingleton

### ISSUE THREAD

**Issue by Eregerog** [XDracam/unity-corelibrary#14]
If you want to use a lazy singeton in edit time and a new instance has to be created, the scene is modified because a new gameobject and component is added.
To my knowledge, the scene has then be marked dirty with 
```
using UnityEditor.SceneManagement;
// ...
#if UNITY_EDITOR
            if (!Application.isPlaying)
                EditorSceneManager.MarkAllScenesDirty();
#endif
```
This would allow lazy singletons to be used during edit time

**Comment by XDracam** [comment]
Going to use `EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());` instead.

**Comment by XDracam** [comment]
@Eregerog is there any reason *not* to use [`Undo.RegisterCreatedObjectUndo`](https://docs.unity3d.com/ScriptReference/Undo.RegisterCreatedObjectUndo.html) instead?

**Comment by Eregerog** [comment]
Those are two different things: Registering an undo has to be called before the modification is made and only allows "stores" the objects current state which can be re-applied by undoing the change.
Mark(AllScenes)Dirty in general tells the editor that an asset has changed, and enables the option to save it.

**Comment by Eregerog** [comment]
> 
> 
> Going to use `EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());` instead.

The things is, there may be multiple scenes active, and you don't know in which active scene the singleton is. Therefore simply mark all scenes dirty
