### ISSUE TITLE
Search.InSiblings / Search.InSiblingsAndChildren

### ISSUE THREAD

**Issue by Eregerog** [XDracam/unity-corelibrary#23]
Does what is says, so one does not have to write transform.parent.Is/All/As<T>(Search.InChildren)

**Comment by XDracam** [comment]
`transform.parent.Is/All/As(Search.InChildren)` is fine and precise, so I will skip on the overly complicated `Search.InSiblingsAndChildren`.

I will implement `Search.InSiblings`, iterating linearlzy through children of the parent including the target itself. This cannot be done elegantly in another way right now.
