### ISSUE TITLE
Add swizzling like in GLSL

### ISSUE THREAD

**Issue by n3roxis** [XDracam/unity-corelibrary#33]
Example:
Vector4 v4 = new Vector4(1,2,3,4);
Vector3 v3 = v4.zxy;    // (3, 1, 2)
Vector2 v2 = v4.yw;    // (2, 4)
Vector3 v3b = v4.yyz; // (2, 2, 4)

**Comment by n3roxis** [comment]
Also for Colors pls!

**Comment by XDracam** [comment]
Done
