### ISSUE TITLE
Dictionary Enumerable Value Extensions aka. Multivalue Dictionary extensions

### ISSUE THREAD

**Issue by Eregerog** [XDracam/unity-corelibrary#53]
Assume we have a Dictionary<TKey, List<TValue>> which is essentially a Multivalue dictionary.
The following extension methods would be useful for both Dict<TKey, IEnumerable<TValue>> and Dict<TKey, ISet<TValue>>:
```
public void Append(TKey k , params TValue[] vs) // Appends to the collection of k, or throws if non-existant
public void Append(TKey k, IEnumerable<TValue> vs)
public void AppendOrAdd(TKey k, params TValue[] vs) // Appends or creates the key entry
public void AppendOrAdd(TKey k, IEnumerable<TValue> vs)
public void Contains(TKey k, TValue v)
public void Remove(TKey k, params[] TValue vs)
public void Remove(TKey k, IEnumerable<TValue> vs)
```
and probably many more that i can't think of right now...

**Comment by XDracam** [comment]
You want a multimap. I am not confident enough to implement a MultiMap that rivals existing collections in performance, stability and elegance.

The problem with C# is that for types `A` and `B` where `B : A` and any type `T`, a `Dictionary<T, B>` is *not* a subclass of `Dictionary<T, A>`. Therefore a `Dictionary<T, List<?>>` is not a `Dictionary<T, IEnumerable<?>>`. 

This means that in the current state of C#, I would have to write and maintain these extension methods for each possible collection implementation. And that is a clear 'hell no'!

I will revisit this once c# collections support proper variance.
