### ISSUE TITLE
Is<>, As<> and All<> on Collisions

### ISSUE THREAD

**Issue by Eregerog** [XDracam/unity-corelibrary#6]
It's faster than writing collision.gameObject.As<>(), and I don't think it would lead to confusion

**Comment by XDracam** [comment]
You can still `collision.transform.As<T>()` if I'm not mistaken

I will consider this for the next update

**Comment by Eregerog** [comment]
Indeed, but it's more code to write and can get quite messy in an if statement, where you just want to check if you collided with an object with a specific script

**Comment by XDracam** [comment]
Bonus: I made these three work on every `Component` as well as any `Collision` to allow more expressive code in the future.
